# Site settings
title: PipelineDP
description: >-
  Write fast, flexible pipelines that use the latest anonymization techniques to
  aggregate user data in a privacy-preserving manner.
baseurl: ""
url: ""
twitter_username: openminedorg
github_username: OpenMined

# Build settings
markdown: kramdown
sass:
  style: compressed
